INSERT INTO Members (
    email_address,
    password,
    title,
    first_name,
    last_name,
    university_id,
    institute_id,
    working_group_id,
    office_room_number,
    office_phone_number,
    office_email_address,
    subscribed
) VALUES (
    $1::TEXT,
    crypt($2::TEXT, gen_salt('md5')),
    $3::TEXT,
    $4::TEXT,
    $5::TEXT,
    $6::INTEGER,
    $7::INTEGER,
    $8::INTEGER,
    $9::TEXT,
    $10::TEXT,
    $11::TEXT,
    $12::BOOLEAN
) RETURNING
    member_id,
    created,
    updated,
    email_address,
    title,
    first_name,
    last_name,
    university_id,
    institute_id,
    working_group_id,
    office_room_number,
    office_phone_number,
    office_email_address,
    admin,
    subscribed
;
