DROP TABLE IF EXISTS Committee CASCADE;

-- SCHEMA
CREATE TABLE Committee (

    -- General
    committee_id SERIAL PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    -- Attributes
    email_address CHARACTER VARYING(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    title CHARACTER VARYING(255) DEFAULT NULL,
    first_name CHARACTER VARYING(255) NOT NULL,
    last_name CHARACTER VARYING(255) NOT NULL,
    institute CHARACTER VARYING(255) DEFAULT NULL,
    research_lab CHARACTER VARYING(255) DEFAULT NULL,
    office_room_number CHARACTER VARYING(255) DEFAULT NULL,
    office_phone_number CHARACTER VARYING(255) DEFAULT NULL,
    office_email_address CHARACTER VARYING(255) DEFAULT NULL,
    admin BOOLEAN DEFAULT false NOT NULL,
    subscribed BOOLEAN DEFAULT true NOT NULL,
    fails SMALLINT DEFAULT 0 NOT NULL

);
