DROP TABLE IF EXISTS Concerns CASCADE;

-- SCHEMA
CREATE TABLE Concerns (

    -- General
    concern_id SERIAL PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    -- Attributes
    revision_id INTEGER NOT NULL REFERENCES Revisions(revision_id) ON UPDATE CASCADE ON DELETE CASCADE,
    q01_value BOOLEAN DEFAULT NULL,
    q01_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q02_value BOOLEAN DEFAULT NULL,
    q02_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q03_value BOOLEAN DEFAULT NULL,
    q03_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q04_value BOOLEAN DEFAULT NULL,
    q04_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q05_value BOOLEAN DEFAULT NULL,
    q05_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q06_value BOOLEAN DEFAULT NULL,
    q06_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q07_value BOOLEAN DEFAULT NULL,
    q07_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q08_value BOOLEAN DEFAULT NULL,
    q08_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q09_value BOOLEAN DEFAULT NULL,
    q09_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q10_value BOOLEAN DEFAULT NULL,
    q10_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q11_value BOOLEAN DEFAULT NULL,
    q11_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q11_2_value BOOLEAN DEFAULT NULL,
    q11_2_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q12_value BOOLEAN DEFAULT NULL,
    q12_explanation CHARACTER VARYING(255) DEFAULT NULL,
    q13_value BOOLEAN DEFAULT NULL,
    q13_explanation CHARACTER VARYING(255) DEFAULT NULL

);
