-- DELETE ALL TABLES
DROP TABLE IF EXISTS Responsibilities CASCADE;
DROP TABLE IF EXISTS Courses CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Members CASCADE;
DROP TABLE IF EXISTS Documents CASCADE;
DROP TABLE IF EXISTS Revisions CASCADE;
DROP TABLE IF EXISTS Descriptions CASCADE;
DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Research_Groups CASCADE;
DROP TABLE IF EXISTS Institutes CASCADE;
DROP TABLE IF EXISTS Universities CASCADE;

-- DELETE ALL EXTENSIONS
DROP EXTENSION IF EXISTS pgcrypto;

-- CREATE EXTENSIONS
CREATE EXTENSION pgcrypto;
